/*Crear usuario Aplicación de checking Documents*/
DROP USER CHECKING_DOCUMENTS CASCADE;

CREATE USER CHECKING_DOCUMENTS IDENTIFIED BY CheckD0c4m3nts1
	DEFAULT TABLESPACE users
	TEMPORARY TABLESPACE temp;

GRANT dba, connect, resource TO CHECKING_DOCUMENTS;